name: Release

on:
  push:
    tags:
      - 'v*'  # This will match tags like v1.0, v20.15.10, etc.


jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        files: |
          dist/*.exe
          dist/*.exe.blockmap
          dist/latest.yml
          dist/win-unpacked/AppNest.exe
          dist/win-unpacked/resources/
          dist/win-unpacked/locales/
          dist/win-unpacked/*.dll
          dist/win-unpacked/*.dat
        generate_release_notes: true
        draft: false
        prerelease: false
